version: "3.7"

services:
  reverseproxy:
    image: jc21/nginx-proxy-manager:2.13.1@sha256:5026ce536dc8dc06601487eaf9a3a9c8dde9841c1751b5ab333c765e2377d54a
    hostname: nginx-proxy-manager_web_1
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/npm-data:/data
      - ${APP_DATA_DIR}/data/letsencrypt:/etc/letsencrypt
